version: '{build}'
branches:
  only:
  - master
  - auto
  - /[\d.]+/
  except:
  - test-truffleruby
skip_tags: true
clone_depth: 10

environment:
  matrix:
  - ruby_version: 23-x64

install: off
test: off
build: off
deploy: off
