version: '{build}'
branches:
  only:
  - master
  - auto
  - /[\d.]+/
skip_tags: true
clone_depth: 10

environment:
  matrix:
  - ruby_version: 23-x64

install: true
test: true
build: off
deploy: off
