name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6.6, truffleruby-head ]
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Run Test
        run: |
          rake setup
          rake test TESTOPTS="-s0 -v"
    timeout-minutes: 60
